name: Pipelines CI

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [ main ]

jobs:    
  build:
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --version-suffix ${{ github.run_number }}

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: deveel/deveel.pipeline

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Pack Libraries
        run: dotnet pack -c Release --include-symbols --include-source -o ./nupkgs --version-suffix ${{ github.run_number }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/deveel/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        
  clean:
    needs: publish
    name: "Clean Old Packages"
    uses: ./.github/workflows/remove-packages.yml