name: Remove Old Packages

on:
  workflow_call:
  
  workflow_dispatch:
  
  
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: "Clean Old Deveel.Pipelines Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Deveel.Pipelines'
          package-type: 'nuget'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
      